[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && pip install --upgrade pip",
  "cd backend && pip install -r requirements.txt",
  "cd backend && npm install --production"
]

[start]
cmd = "cd backend && python3 app.py"
